### ISSUE TITLE
Arma Server Tracker

### ISSUE THREAD

**Issue by Saborknight** [Saborknight/7thaa-website#4]
Show's the Arma 3 server, who's on it, the IP, etc. (See list below)

## Must Show
- [ ] Mission loaded up
- [ ] Number of players
- [ ] IP of server
- [ ] Ping from local computer
- [ ] Scoreboard

**Comment by Saborknight** [comment]
arma3-servers.net For html banners and statistics. I have yet to find something to generate a scoreboard though I suspect this could be fetched directly from the server, bypassing the 3rd party banner website.

Need to look in to it more.
(Original comment: 25 May 2016)

**Comment by Saborknight** [comment]
Right now I'm just migrating old tasks. You're right. Scoreboard doesn't make sense in our situation at all.

**Comment by GhostTheSlayer** [comment]
I can take a look at this if you mean the banners from gametracker/battlemetrics, tho they don't show ping.

**Comment by Saborknight** [comment]
I think those banners will do fine for now. This ticket is extremely old (Created on 22 May 2016!) so I can't remember what I was thinking about specifically, but I do think I was going along the lines of showing the indivindual stats of each person on their profile? Maybe.

**Comment by TheNightstalk3r** [comment]
With the pro version of the battlemetrics I can get even some custom banners

**Comment by Saborknight** [comment]
@TheNightstalk3r go ahead and get them, @GhostTheSlayer will implement. Post the code here for him.

**Comment by GhostTheSlayer** [comment]
![image](https://user-images.githubusercontent.com/38784343/39401828-b97e9096-4b3e-11e8-939f-bab288768629.png)
![image](https://user-images.githubusercontent.com/38784343/39401831-c225d308-4b3e-11e8-87dd-92ba336cc6ac.png)

Like with the servers where is used to say alpha maps and mods....
You want text next to the tracker like Alpha.. or Alpha private zeus ops modpack...?
Becouse text more than like Alpha seems poinless for me since the tracker gives the server name.

**Comment by TheNightstalk3r** [comment]
Alpha: <script type="application/javascript">window.addEventListener('message',function(e){if(e.data.uid&&e.data.type==='sizeUpdate'){var i = document.querySelector('iframe[name="'+e.data.uid+'"]');i.style.width = e.data.payload.width;i.style.height = e.data.payload.height;}});</script><iframe src="https://cdn.battlemetrics.com/b/HJJIY9Naz/698012.html?_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTA3NSwic2VydmVyIjo2OTgwMTIsIm9wdGlvbnMiOnsiZm9yZWdyb3VuZCI6IiNFRUVFRUUiLCJsaW5rQ29sb3IiOiIjMTE4NWVjIiwibGluZXMiOiIjMzMzMzMzIiwiYmFja2dyb3VuZCI6IiMyMjIyMjIiLCJjaGFydCI6InBsYXllcnM6MjRIIiwiY2hhcnRDb2xvciI6IiNGRjA3MDAiLCJtYXhQbGF5ZXJzSGVpZ2h0IjoiMzAwIn0sImxpdmVVcGRhdGVzIjp0cnVlLCJ1c2VyX2lkIjo2NjU3LCJpYXQiOjE1MjUwOTUzMzd9.OjZa9ZnpuKURMpiDU8SFDgf59JW56LEDnpbjIiT64LQ" frameborder=0 style="border:0" name="skrxc"></iframe>

Bravo: 
<script type="application/javascript">window.addEventListener('message',function(e){if(e.data.uid&&e.data.type==='sizeUpdate'){var i = document.querySelector('iframe[name="'+e.data.uid+'"]');i.style.width = e.data.payload.width;i.style.height = e.data.payload.height;}});</script><iframe src="https://cdn.battlemetrics.com/b/HJJIY9Naz/615338.html?_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTA3NSwic2VydmVyIjo2MTUzMzgsIm9wdGlvbnMiOnsiZm9yZWdyb3VuZCI6IiNFRUVFRUUiLCJsaW5rQ29sb3IiOiIjMTE4NWVjIiwibGluZXMiOiIjMzMzMzMzIiwiYmFja2dyb3VuZCI6IiMyMjIyMjIiLCJjaGFydCI6InBsYXllcnM6MjRIIiwiY2hhcnRDb2xvciI6IiNGRjA3MDAiLCJtYXhQbGF5ZXJzSGVpZ2h0IjoiMzAwIn0sImxpdmVVcGRhdGVzIjp0cnVlLCJ1c2VyX2lkIjo2NjU3LCJpYXQiOjE1MjUwOTUzODh9.Oieyt_N2x5OuYnBmUlMlz_AKAaqNHNgKovJC2eGsvwI" frameborder=0 style="border:0" name="wyqos"></iframe>

Charlie: <script type="application/javascript">window.addEventListener('message',function(e){if(e.data.uid&&e.data.type==='sizeUpdate'){var i = document.querySelector('iframe[name="'+e.data.uid+'"]');i.style.width = e.data.payload.width;i.style.height = e.data.payload.height;}});</script><iframe src="https://cdn.battlemetrics.com/b/HJJIY9Naz/287661.html?_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTA3NSwic2VydmVyIjoyODc2NjEsIm9wdGlvbnMiOnsiZm9yZWdyb3VuZCI6IiNFRUVFRUUiLCJsaW5rQ29sb3IiOiIjMTE4NWVjIiwibGluZXMiOiIjMzMzMzMzIiwiYmFja2dyb3VuZCI6IiMyMjIyMjIiLCJjaGFydCI6InBsYXllcnM6MjRIIiwiY2hhcnRDb2xvciI6IiNGRjA3MDAiLCJtYXhQbGF5ZXJzSGVpZ2h0IjoiMzAwIn0sImxpdmVVcGRhdGVzIjp0cnVlLCJ1c2VyX2lkIjo2NjU3LCJpYXQiOjE1MjUwOTU0MTJ9.j_tBRsXzVzYjDXfSf4lX3MXzyZECSZhOn6VZT3GfR7s" frameborder=0 style="border:0" name="chbzo"></iframe>

Delta: <script type="application/javascript">window.addEventListener('message',function(e){if(e.data.uid&&e.data.type==='sizeUpdate'){var i = document.querySelector('iframe[name="'+e.data.uid+'"]');i.style.width = e.data.payload.width;i.style.height = e.data.payload.height;}});</script><iframe src="https://cdn.battlemetrics.com/b/HJJIY9Naz/727222.html?_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTA3NSwic2VydmVyIjo3MjcyMjIsIm9wdGlvbnMiOnsiZm9yZWdyb3VuZCI6IiNFRUVFRUUiLCJsaW5rQ29sb3IiOiIjMTE4NWVjIiwibGluZXMiOiIjMzMzMzMzIiwiYmFja2dyb3VuZCI6IiMyMjIyMjIiLCJjaGFydCI6InBsYXllcnM6MjRIIiwiY2hhcnRDb2xvciI6IiNGRjA3MDAiLCJtYXhQbGF5ZXJzSGVpZ2h0IjoiMzAwIn0sImxpdmVVcGRhdGVzIjp0cnVlLCJ1c2VyX2lkIjo2NjU3LCJpYXQiOjE1MjUwOTU0MjZ9.JDJyalqFR4Ju6M_Q39u6ikHA1uGAKi50qDa-LZfPn5M" frameborder=0 style="border:0" name="bmmuz"></iframe>

Echo: <script type="application/javascript">window.addEventListener('message',function(e){if(e.data.uid&&e.data.type==='sizeUpdate'){var i = document.querySelector('iframe[name="'+e.data.uid+'"]');i.style.width = e.data.payload.width;i.style.height = e.data.payload.height;}});</script><iframe src="https://cdn.battlemetrics.com/b/HJJIY9Naz/1982844.html?_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTA3NSwic2VydmVyIjoxOTgyODQ0LCJvcHRpb25zIjp7ImZvcmVncm91bmQiOiIjRUVFRUVFIiwibGlua0NvbG9yIjoiIzExODVlYyIsImxpbmVzIjoiIzMzMzMzMyIsImJhY2tncm91bmQiOiIjMjIyMjIyIiwiY2hhcnQiOiJwbGF5ZXJzOjI0SCIsImNoYXJ0Q29sb3IiOiIjRkYwNzAwIiwibWF4UGxheWVyc0hlaWdodCI6IjMwMCJ9LCJsaXZlVXBkYXRlcyI6dHJ1ZSwidXNlcl9pZCI6NjY1NywiaWF0IjoxNTI1MDk1NDQ2fQ.RWdgoiakHUFcO_GH5vwZnAhUnhdgApCgA_WanPQLT5k" frameborder=0 style="border:0" name="bdtpq"></iframe>

Foxtrot: <script type="application/javascript">window.addEventListener('message',function(e){if(e.data.uid&&e.data.type==='sizeUpdate'){var i = document.querySelector('iframe[name="'+e.data.uid+'"]');i.style.width = e.data.payload.width;i.style.height = e.data.payload.height;}});</script><iframe src="https://cdn.battlemetrics.com/b/HJJIY9Naz/2202886.html?_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTA3NSwic2VydmVyIjoyMjAyODg2LCJvcHRpb25zIjp7ImZvcmVncm91bmQiOiIjRUVFRUVFIiwibGlua0NvbG9yIjoiIzExODVlYyIsImxpbmVzIjoiIzMzMzMzMyIsImJhY2tncm91bmQiOiIjMjIyMjIyIiwiY2hhcnQiOiJwbGF5ZXJzOjI0SCIsImNoYXJ0Q29sb3IiOiIjRkYwNzAwIiwibWF4UGxheWVyc0hlaWdodCI6IjMwMCJ9LCJsaXZlVXBkYXRlcyI6dHJ1ZSwidXNlcl9pZCI6NjY1NywiaWF0IjoxNTI1MDk1NDU2fQ.EHDogq9flAgIehnH4WKcsZNeZjbIMnrQwSpbW9FfR5k" frameborder=0 style="border:0" name="njwqb"></iframe>

Golf: <script type="application/javascript">window.addEventListener('message',function(e){if(e.data.uid&&e.data.type==='sizeUpdate'){var i = document.querySelector('iframe[name="'+e.data.uid+'"]');i.style.width = e.data.payload.width;i.style.height = e.data.payload.height;}});</script><iframe src="https://cdn.battlemetrics.com/b/HJJIY9Naz/2202887.html?_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTA3NSwic2VydmVyIjoyMjAyODg3LCJvcHRpb25zIjp7ImZvcmVncm91bmQiOiIjRUVFRUVFIiwibGlua0NvbG9yIjoiIzExODVlYyIsImxpbmVzIjoiIzMzMzMzMyIsImJhY2tncm91bmQiOiIjMjIyMjIyIiwiY2hhcnQiOiJwbGF5ZXJzOjI0SCIsImNoYXJ0Q29sb3IiOiIjRkYwNzAwIiwibWF4UGxheWVyc0hlaWdodCI6IjMwMCJ9LCJsaXZlVXBkYXRlcyI6dHJ1ZSwidXNlcl9pZCI6NjY1NywiaWF0IjoxNTI1MDk1NDY3fQ.V37_q5i-E_EzvPuJSDFAfE_a483sGEhCA833PkWiAPs" frameborder=0 style="border:0" name="lcyuf"></iframe>

**Comment by TheNightstalk3r** [comment]
Will change if we change the contents of the banner!

**Comment by GhostTheSlayer** [comment]
`<script type="application/javascript">window.addEventListener('message',function(e){if(e.data.uid&&e.data.type==='sizeUpdate'){var i = document.querySelector('iframe[name="'+e.data.uid+'"]');i.style.width = e.data.payload.width;i.style.height = e.data.payload.height;}});</script><iframe src="https://cdn.battlemetrics.com/b/S1J7ktcKZ/698012.html?foreground=%23EEEEEE&background=%23222222&lines=%23333333&linkColor=%231185ec&chartColor=%23FF0700" frameborder=0 style="border:0" name="tgqoh"></iframe>

<script type="application/javascript">window.addEventListener('message',function(e){if(e.data.uid&&e.data.type==='sizeUpdate'){var i = document.querySelector('iframe[name="'+e.data.uid+'"]');i.style.width = e.data.payload.width;i.style.height = e.data.payload.height;}});</script><iframe src="https://cdn.battlemetrics.com/b/S1J7ktcKZ/615338.html?_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NzY4LCJzZXJ2ZXIiOjYxNTMzOCwib3B0aW9ucyI6eyJmb3JlZ3JvdW5kIjoiI0VFRUVFRSIsImJhY2tncm91bmQiOiIjMjIyMjIyIiwibGluZXMiOiIjMzMzMzMzIiwibGlua0NvbG9yIjoiIzExODVlYyIsImNoYXJ0Q29sb3IiOiIjRkYwNzAwIn0sImxpdmVVcGRhdGVzIjp0cnVlLCJ1c2VyX2lkIjo2NjU3LCJpYXQiOjE1MjUxMDM1NzR9.Vbkjrp6Jxe9kcJV1puNPTdjKwH9SM7n33eBoxNv6ovs" frameborder=0 style="border:0" name="oycom"></iframe>

<script type="application/javascript">window.addEventListener('message',function(e){if(e.data.uid&&e.data.type==='sizeUpdate'){var i = document.querySelector('iframe[name="'+e.data.uid+'"]');i.style.width = e.data.payload.width;i.style.height = e.data.payload.height;}});</script><iframe src="https://cdn.battlemetrics.com/b/S1J7ktcKZ/287661.html?_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NzY4LCJzZXJ2ZXIiOjYxNTMzOCwib3B0aW9ucyI6eyJmb3JlZ3JvdW5kIjoiI0VFRUVFRSIsImJhY2tncm91bmQiOiIjMjIyMjIyIiwibGluZXMiOiIjMzMzMzMzIiwibGlua0NvbG9yIjoiIzExODVlYyIsImNoYXJ0Q29sb3IiOiIjRkYwNzAwIn0sImxpdmVVcGRhdGVzIjp0cnVlLCJ1c2VyX2lkIjo2NjU3LCJpYXQiOjE1MjUxMDM1OTJ9.iFsP0fAuGcSZ8C-es0VKpedsCnlB6HM5IuIepMyjg8U" frameborder=0 style="border:0" name="jgrdk"></iframe>

<script type="application/javascript">window.addEventListener('message',function(e){if(e.data.uid&&e.data.type==='sizeUpdate'){var i = document.querySelector('iframe[name="'+e.data.uid+'"]');i.style.width = e.data.payload.width;i.style.height = e.data.payload.height;}});</script><iframe src="https://cdn.battlemetrics.com/b/S1J7ktcKZ/727222.html?_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NzY4LCJzZXJ2ZXIiOjcyNzIyMiwib3B0aW9ucyI6eyJmb3JlZ3JvdW5kIjoiI0VFRUVFRSIsImJhY2tncm91bmQiOiIjMjIyMjIyIiwibGluZXMiOiIjMzMzMzMzIiwibGlua0NvbG9yIjoiIzExODVlYyIsImNoYXJ0Q29sb3IiOiIjRkYwNzAwIn0sImxpdmVVcGRhdGVzIjp0cnVlLCJ1c2VyX2lkIjo2NjU3LCJpYXQiOjE1MjUxMDM1OTl9.tP7iC8VzIHX-h-M8WhpB4EZ9XD2M-fxa4gOnkId0dGA" frameborder=0 style="border:0" name="kxddu"></iframe>

<script type="application/javascript">window.addEventListener('message',function(e){if(e.data.uid&&e.data.type==='sizeUpdate'){var i = document.querySelector('iframe[name="'+e.data.uid+'"]');i.style.width = e.data.payload.width;i.style.height = e.data.payload.height;}});</script><iframe src="https://cdn.battlemetrics.com/b/S1J7ktcKZ/1982844.html?_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NzY4LCJzZXJ2ZXIiOjE5ODI4NDQsIm9wdGlvbnMiOnsiZm9yZWdyb3VuZCI6IiNFRUVFRUUiLCJiYWNrZ3JvdW5kIjoiIzIyMjIyMiIsImxpbmVzIjoiIzMzMzMzMyIsImxpbmtDb2xvciI6IiMxMTg1ZWMiLCJjaGFydENvbG9yIjoiI0ZGMDcwMCJ9LCJsaXZlVXBkYXRlcyI6dHJ1ZSwidXNlcl9pZCI6NjY1NywiaWF0IjoxNTI1MTAzNjA1fQ.8qkRwXgoJ24Chijp4xJbn5f4HGv6HdITUsEkIMoDzNI" frameborder=0 style="border:0" name="cqosr"></iframe>

<script type="application/javascript">window.addEventListener('message',function(e){if(e.data.uid&&e.data.type==='sizeUpdate'){var i = document.querySelector('iframe[name="'+e.data.uid+'"]');i.style.width = e.data.payload.width;i.style.height = e.data.payload.height;}});</script><iframe src="https://cdn.battlemetrics.com/b/S1J7ktcKZ/2202886.html?_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NzY4LCJzZXJ2ZXIiOjIyMDI4ODYsIm9wdGlvbnMiOnsiZm9yZWdyb3VuZCI6IiNFRUVFRUUiLCJiYWNrZ3JvdW5kIjoiIzIyMjIyMiIsImxpbmVzIjoiIzMzMzMzMyIsImxpbmtDb2xvciI6IiMxMTg1ZWMiLCJjaGFydENvbG9yIjoiI0ZGMDcwMCJ9LCJsaXZlVXBkYXRlcyI6dHJ1ZSwidXNlcl9pZCI6NjY1NywiaWF0IjoxNTI1MTAzNjEwfQ.6rjEhF_EnF-LutJvh3kK7jcLSodSx3OSj0SgHOOumAc" frameborder=0 style="border:0" name="dpznj"></iframe>

<script type="application/javascript">window.addEventListener('message',function(e){if(e.data.uid&&e.data.type==='sizeUpdate'){var i = document.querySelector('iframe[name="'+e.data.uid+'"]');i.style.width = e.data.payload.width;i.style.height = e.data.payload.height;}});</script><iframe src="https://cdn.battlemetrics.com/b/S1J7ktcKZ/2202886.html?_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NzY4LCJzZXJ2ZXIiOjIyMDI4ODYsIm9wdGlvbnMiOnsiZm9yZWdyb3VuZCI6IiNFRUVFRUUiLCJiYWNrZ3JvdW5kIjoiIzIyMjIyMiIsImxpbmVzIjoiIzMzMzMzMyIsImxpbmtDb2xvciI6IiMxMTg1ZWMiLCJjaGFydENvbG9yIjoiI0ZGMDcwMCJ9LCJsaXZlVXBkYXRlcyI6dHJ1ZSwidXNlcl9pZCI6NjY1NywiaWF0IjoxNTI1MTAzNjEwfQ.6rjEhF_EnF-LutJvh3kK7jcLSodSx3OSj0SgHOOumAc" frameborder=0 style="border:0" name="dpznj"></iframe>`

**Comment by GhostTheSlayer** [comment]
`test`

**Comment by GhostTheSlayer** [comment]
```<script type="application/javascript">window.addEventListener('message',function(e){if(e.data.uid&&e.data.type==='sizeUpdate'){var i = document.querySelector('iframe[name="'+e.data.uid+'"]');i.style.width = e.data.payload.width;i.style.height = e.data.payload.height;}});</script><iframe src="https://cdn.battlemetrics.com/b/SJOHlA4TM/2202887.html?_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTA3Niwic2VydmVyIjoyMjAyODg3LCJvcHRpb25zIjp7ImZvcmVncm91bmQiOiIjRUVFRUVFIiwiYmFja2dyb3VuZCI6IiMyMjIyMjIiLCJsaW5lcyI6IiMzMzMzMzMiLCJsaW5rQ29sb3IiOiIjMTE4NWVjIiwiY2hhcnRDb2xvciI6IiNGRjA3MDAifSwibGl2ZVVwZGF0ZXMiOnRydWUsInVzZXJfaWQiOjY2NTcsImlhdCI6MTUyNTExNDQ0MX0.0_bgMDK00wXilX_DB726zhgI7pRinHCPJH0TJIglbTY" frameborder=0 style="border:0" name="lpixc"></iframe>```
